run:
  deadline: 5m
  issues-exit-code: 1

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - lll
    - unparam
    - goconst
    - tagliatelle
    - wrapcheck
    - exhaustivestruct
    - gosec
    - noctx
    - gofumpt
    - gci
    - goimports
linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: compiler
  gocritic:
    enabled-tags:
      - experimental
    disabled-tags:
      - opinionated